on region exit:
    if player doesn't have permission "*":
        if player is in world "Spawn":
            wait 1 tick
            set {_Cords::OutofMap} to location of player
            if "%region at player%" is "<none>":
                execute player command "/spawn"
                play sound "entity.villager.no" to the player
                send "&cYou cannot escape the map! If you believe this is an error, please report these cordinates: &e%{_Cords::OutofMap}% &cto an Admin on Discord!"